USE [IAM_LocalTest];
GO
SET ANSI_NULLS ON; SET QUOTED_IDENTIFIER ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET CONCAT_NULL_YIELDS_NULL ON; SET ARITHABORT ON; SET NUMERIC_ROUNDABORT OFF; SET NOCOUNT ON; SET XACT_ABORT ON;
IF DB_NAME() <> N'IAM_LocalTest' THROW 51000, 'Wrong database selected.', 1;
BEGIN TRANSACTION;
DECLARE @OrganizationId bigint = (SELECT OrganizationId FROM [Identity].[OrganizationUnit] WHERE UnitType=N'Organization' AND UnitName=N'AMS Test Organization' AND IsActive=1);
IF @OrganizationId IS NULL THROW 51001, 'AMS Test Organization was not found.', 1;
DECLARE @Locations TABLE(BranchName nvarchar(400), LocationName nvarchar(400), LocationCode nvarchar(100), PRIMARY KEY(BranchName,LocationName));
INSERT @Locations VALUES (N'Central Service Warehouse',N'Central Service WH_Chennai',N'LOC-BL-0001');
INSERT @Locations VALUES (N'Central Service Warehouse',N'Central Service_Chennai',N'LOC-BL-0002');
INSERT @Locations VALUES (N'Delivery Center',N'Delivery Center_QC',N'LOC-BL-0003');
INSERT @Locations VALUES (N'Delivery Center',N'Delivery Center_QC_ULDC warehouse',N'LOC-BL-0004');
INSERT @Locations VALUES (N'Delivery Center',N'Delivery Center_ULDC Warehouse',N'LOC-BL-0005');
INSERT @Locations VALUES (N'Fujitec Ahmedabad',N'Ahmedabad_Engineer',N'LOC-BL-0006');
INSERT @Locations VALUES (N'Fujitec Ahmedabad',N'Ahmedabad_Install',N'LOC-BL-0007');
INSERT @Locations VALUES (N'Fujitec Ahmedabad',N'Ahmedabad_IT',N'LOC-BL-0008');
INSERT @Locations VALUES (N'Fujitec Ahmedabad',N'Ahmedabad_Office',N'LOC-BL-0009');
INSERT @Locations VALUES (N'Fujitec Ahmedabad',N'Ahmedabad_Sales',N'LOC-BL-0010');
INSERT @Locations VALUES (N'Fujitec Ahmedabad',N'Factory&HO_IT',N'LOC-BL-0011');
INSERT @Locations VALUES (N'Fujitec Andhra Pradesh',N'Andhra Pradesh_Install',N'LOC-BL-0012');
INSERT @Locations VALUES (N'Fujitec Andhra Pradesh',N'Vijayawad_Install',N'LOC-BL-0013');
INSERT @Locations VALUES (N'Fujitec Andhra Pradesh',N'Vijayawada_Install',N'LOC-BL-0014');
INSERT @Locations VALUES (N'Fujitec Andhra Pradesh',N'Vijayawada_IT',N'LOC-BL-0015');
INSERT @Locations VALUES (N'Fujitec Andhra Pradesh',N'Vijayawada_Office',N'LOC-BL-0016');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Bangalore-IT',N'LOC-BL-0017');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Bangalore_Admin',N'LOC-BL-0018');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Bangalore_Install',N'LOC-BL-0019');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Bangalore_IT',N'LOC-BL-0020');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Bangalore_Office',N'LOC-BL-0021');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Bangalore_QC',N'LOC-BL-0022');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Bangalore_Safety',N'LOC-BL-0023');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Bangalore_Sales',N'LOC-BL-0024');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Bangalore_Service',N'LOC-BL-0025');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Mangalore_Install',N'LOC-BL-0026');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Mangalore_Office',N'LOC-BL-0027');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Mumbai1_Service',N'LOC-BL-0028');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Mysore_Office',N'LOC-BL-0029');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Chennai_ Office',N'LOC-BL-0030');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Chennai_Admin',N'LOC-BL-0031');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Chennai_Br Manager',N'LOC-BL-0032');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Chennai_Finance',N'LOC-BL-0033');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Chennai_Install',N'LOC-BL-0034');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Chennai_IT',N'LOC-BL-0035');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Chennai_Office',N'LOC-BL-0036');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Chennai_Sales',N'LOC-BL-0037');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Chennai_Service',N'LOC-BL-0038');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Chennai_Trichy',N'LOC-BL-0039');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Coimbatore_Office',N'LOC-BL-0040');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Factory&HO_IT',N'LOC-BL-0041');
INSERT @Locations VALUES (N'Fujitec CMRL',N'CMRL Office',N'LOC-BL-0042');
INSERT @Locations VALUES (N'Fujitec CMRL',N'CMRL_Container Office',N'LOC-BL-0043');
INSERT @Locations VALUES (N'Fujitec CMRL',N'CMRL_Install',N'LOC-BL-0044');
INSERT @Locations VALUES (N'Fujitec CMRL',N'CMRL_IT',N'LOC-BL-0045');
INSERT @Locations VALUES (N'Fujitec CMRL',N'CMRL_Office',N'LOC-BL-0046');
INSERT @Locations VALUES (N'Fujitec Cochin',N'Cochin_Admin',N'LOC-BL-0047');
INSERT @Locations VALUES (N'Fujitec Cochin',N'Cochin_Install',N'LOC-BL-0048');
INSERT @Locations VALUES (N'Fujitec Cochin',N'Cochin_IT',N'LOC-BL-0049');
INSERT @Locations VALUES (N'Fujitec Cochin',N'Cochin_Office',N'LOC-BL-0050');
INSERT @Locations VALUES (N'Fujitec Cochin',N'Cochin_Sales',N'LOC-BL-0051');
INSERT @Locations VALUES (N'Fujitec Cochin',N'Cochin_Service',N'LOC-BL-0052');
INSERT @Locations VALUES (N'Fujitec Cochin',N'Thulasidas_Sales',N'LOC-BL-0053');
INSERT @Locations VALUES (N'Fujitec Delhi',N'Delhi_Install',N'LOC-BL-0054');
INSERT @Locations VALUES (N'Fujitec Delhi',N'Delhi_IT',N'LOC-BL-0055');
INSERT @Locations VALUES (N'Fujitec Delhi',N'Delhi_Office',N'LOC-BL-0056');
INSERT @Locations VALUES (N'Fujitec Delhi',N'Delhi_safety',N'LOC-BL-0057');
INSERT @Locations VALUES (N'Fujitec Delhi',N'Delhi_Sales',N'LOC-BL-0058');
INSERT @Locations VALUES (N'Fujitec Delhi',N'Delhi_Service',N'LOC-BL-0059');
INSERT @Locations VALUES (N'Fujitec Delhi',N'Factory&HO_IT',N'LOC-BL-0060');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'1 Security room & 1 Maintn',N'LOC-BL-0061');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'1no South side Security Room & 9EPL',N'LOC-BL-0062');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'At New Amada Machines_Factory',N'LOC-BL-0063');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'At weight machine_Factory',N'LOC-BL-0064');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building 2_Office Green Workstations',N'LOC-BL-0065');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building 2_Office Orange Workstations',N'LOC-BL-0066');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1',N'LOC-BL-0067');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1 G flr Northwing_Womens restroom',N'LOC-BL-0068');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1 terrace',N'LOC-BL-0069');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1-Canteen',N'LOC-BL-0070');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1-G flr North Orange workstations',N'LOC-BL-0071');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1-G flr Northwing Green workstation',N'LOC-BL-0072');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_ G flr Northwing',N'LOC-BL-0073');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Floor Sports room',N'LOC-BL-0074');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Floor_Canteen',N'LOC-BL-0075');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st flr 23 Saffron',N'LOC-BL-0076');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Flr Cabin 25 Lilac',N'LOC-BL-0077');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Flr Cabin 27 Primorse',N'LOC-BL-0078');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Flr Cabin 28 Jarul',N'LOC-BL-0079');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Flr IT store',N'LOC-BL-0080');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st flr Northwing Green',N'LOC-BL-0081');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st flr Northwing orange workstations',N'LOC-BL-0082');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st flr Northwing Womens restroom',N'LOC-BL-0083');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Flr Southwing Workstations',N'LOC-BL-0084');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Flr_30 Morning Glory',N'LOC-BL-0085');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Flr_dry pantry',N'LOC-BL-0086');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Flr_Finance Recrd room 1',N'LOC-BL-0087');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Flr_Finance Recrd room 2',N'LOC-BL-0088');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Flr_Northwing Rest room',N'LOC-BL-0089');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Flr_Northwing_Discussion table 1',N'LOC-BL-0090');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st flr_SouthWing',N'LOC-BL-0091');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st flr_Southwing toilet',N'LOC-BL-0092');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st flr_Southwing_Discus table 1',N'LOC-BL-0093');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st flr_Southwing_Discus table 2',N'LOC-BL-0094');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st flr_Southwing_Green',N'LOC-BL-0095');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st flr_Southwing_Orange',N'LOC-BL-0096');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1stFlr 26 Lotus',N'LOC-BL-0097');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1stFlr 29 Jasmine',N'LOC-BL-0098');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1stFlr_24 Buttercups',N'LOC-BL-0099');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1stFlr_Northwing',N'LOC-BL-0100');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1stFlr_Northwing_Discussion table 2',N'LOC-BL-0101');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1stFlr_Northwing_Green',N'LOC-BL-0102');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1stFlr_Northwing_Orange',N'LOC-BL-0103');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Cabin 31',N'LOC-BL-0104');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Canteen',N'LOC-BL-0105');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_ETP',N'LOC-BL-0106');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Factory Wings',N'LOC-BL-0107');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Factory_Admin',N'LOC-BL-0108');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Factory_HOD',N'LOC-BL-0109');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Factory_O2 N2 GAS PLANT FRONT SIDE',N'LOC-BL-0110');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Factory_PLANT 1 NORTH EAST CORNER',N'LOC-BL-0111');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Factory_PLANT 1 OFFICE 1',N'LOC-BL-0112');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Factory_PLANT 1 OFFICE 2',N'LOC-BL-0113');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Factory_PLANT 1 RECEPTION OUTSIDE',N'LOC-BL-0114');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Factory_PLANT 1 RECPECTION',N'LOC-BL-0115');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Fist AID room',N'LOC-BL-0116');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G & 1st Floor',N'LOC-BL-0117');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G & 1st Floors',N'LOC-BL-0118');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G & 1st Flr Office&canteen area',N'LOC-BL-0119');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G Flr cabin 31 Alfalfa',N'LOC-BL-0120');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G flr Conference room',N'LOC-BL-0121');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G flr Green workstations',N'LOC-BL-0122');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G flr North side Staircase',N'LOC-BL-0123');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G Flr Northwing Discussion Table 1',N'LOC-BL-0124');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G flr Northwing Restroom',N'LOC-BL-0125');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G flr Orange Workstations',N'LOC-BL-0126');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G flr penal room',N'LOC-BL-0127');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G Flr_Discussion Table 2',N'LOC-BL-0128');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G flr_Manager cabin1',N'LOC-BL-0129');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G flr_Manager cabin2',N'LOC-BL-0130');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Gfloor UPS room',N'LOC-BL-0131');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Gfloor- Northwing',N'LOC-BL-0132');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Ground Floor',N'LOC-BL-0133');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Head office_Mr.Gopal',N'LOC-BL-0134');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_House keeping Room',N'LOC-BL-0135');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_HR&Admin',N'LOC-BL-0136');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_IT Server room',N'LOC-BL-0137');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Maintenance Depart',N'LOC-BL-0138');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_MPL',N'LOC-BL-0139');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_MPL 1nos& Dry Pantry1nos',N'LOC-BL-0140');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_MPL @Robot welding',N'LOC-BL-0141');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_MPL GANG WAY-1',N'LOC-BL-0142');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_MPL LD Conveyor Line 2',N'LOC-BL-0143');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_MPL next to O2&N2 Gas plant',N'LOC-BL-0144');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_MPL-Assembly & Packing',N'LOC-BL-0145');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_MPL_Jamb Assy',N'LOC-BL-0146');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_MPL_near  to DG set',N'LOC-BL-0147');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_MPL_Robotic Welding',N'LOC-BL-0148');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_MPL_Salvagnini_Bonding line',N'LOC-BL-0149');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_northside Carparking area',N'LOC-BL-0150');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Northwing',N'LOC-BL-0151');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Parking_Factory',N'LOC-BL-0152');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_PCP',N'LOC-BL-0153');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_PCP near',N'LOC-BL-0154');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_PCP_Lab',N'LOC-BL-0155');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_PCP_PT Line',N'LOC-BL-0156');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_PCP_QC',N'LOC-BL-0157');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Quality Hall',N'LOC-BL-0158');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Receiption area',N'LOC-BL-0159');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_RMS Room',N'LOC-BL-0160');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Stationery room',N'LOC-BL-0161');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Test tower lift front side',N'LOC-BL-0162');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Test tower machine room',N'LOC-BL-0163');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Training center',N'LOC-BL-0164');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Yabuchi',N'LOC-BL-0165');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2',N'LOC-BL-0166');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2 cabin_Maintenance',N'LOC-BL-0167');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_ 1st Flr Record room 3',N'LOC-BL-0168');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_ at Weighment',N'LOC-BL-0169');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_ IT Server room',N'LOC-BL-0170');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_ near to cafetaria Restroom',N'LOC-BL-0171');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_ North G Floor Pantry',N'LOC-BL-0172');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_ Office Orange workstations',N'LOC-BL-0173');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_1st  flr South side',N'LOC-BL-0174');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_1st floor North side',N'LOC-BL-0175');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_1st flr dry Pantry',N'LOC-BL-0176');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_1st flr mens restroom',N'LOC-BL-0177');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_1st Flr Record room 1',N'LOC-BL-0178');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_1st Flr Record room 2',N'LOC-BL-0179');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_1st Flr Record room 3',N'LOC-BL-0180');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_1st Flr Record room 4',N'LOC-BL-0181');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_AC Pannel room',N'LOC-BL-0182');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Air Condition',N'LOC-BL-0183');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_at Door access reader',N'LOC-BL-0184');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 1 Rudrapushpa',N'LOC-BL-0185');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 10 Kumudini',N'LOC-BL-0186');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 11 Rose',N'LOC-BL-0187');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 12 Suryakanti',N'LOC-BL-0188');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 13 Tulip',N'LOC-BL-0189');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 14 Daisy',N'LOC-BL-0190');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 15 Lavender',N'LOC-BL-0191');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 16 Poppy',N'LOC-BL-0192');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 17 Orchid',N'LOC-BL-0193');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 18 Aster',N'LOC-BL-0194');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 19 Daffodil',N'LOC-BL-0195');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 2 Marigold',N'LOC-BL-0196');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 20 Iris',N'LOC-BL-0197');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 21 Zinnia',N'LOC-BL-0198');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 22 Camellia',N'LOC-BL-0199');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 3 Kamal',N'LOC-BL-0200');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 4 Ashok',N'LOC-BL-0201');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 5 Pansy',N'LOC-BL-0202');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 6 Dahlia',N'LOC-BL-0203');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 7 Navmallika',N'LOC-BL-0204');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 8 Neel Kamal',N'LOC-BL-0205');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 9 Champakam',N'LOC-BL-0206');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Canteeen',N'LOC-BL-0207');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Canteen',N'LOC-BL-0208');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Canteen dining',N'LOC-BL-0209');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Canteen_VIP dining room',N'LOC-BL-0210');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_CMRL room',N'LOC-BL-0211');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Eastsouth corner',N'LOC-BL-0212');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Entire building',N'LOC-BL-0213');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Entire electrical work',N'LOC-BL-0214');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_EPL',N'LOC-BL-0215');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_EPL Conveyor Line',N'LOC-BL-0216');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_EPL COP assembly',N'LOC-BL-0217');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_EPL Entrance',N'LOC-BL-0218');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_EPL Packing Area',N'LOC-BL-0219');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_EPL south Entrance',N'LOC-BL-0220');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_EPL Test Jig',N'LOC-BL-0221');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_EPL Warehouse',N'LOC-BL-0222');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Factory_Warehouse',N'LOC-BL-0223');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_First Aid Room',N'LOC-BL-0224');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Frente side',N'LOC-BL-0225');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_G flr South side Office door',N'LOC-BL-0226');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Gfloor near to Escalator',N'LOC-BL-0227');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Gfloor North side',N'LOC-BL-0228');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Guide Rail Storage Yard',N'LOC-BL-0229');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_House keeping store',N'LOC-BL-0230');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_IT Depart',N'LOC-BL-0231');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Library Cabin area',N'LOC-BL-0232');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_MPL',N'LOC-BL-0233');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_MWC warehouse',N'LOC-BL-0234');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_MWC Warehouse inside',N'LOC-BL-0235');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_MWC Warehouse Locker Room',N'LOC-BL-0236');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_MWC warehouse North side door',N'LOC-BL-0237');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_MWC warehouse Northside',N'LOC-BL-0238');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_MWC Warehouse Office',N'LOC-BL-0239');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_MWC warehouse south side door',N'LOC-BL-0240');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_MWC warehouse southside',N'LOC-BL-0241');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_MWC Warehouse_Packing area',N'LOC-BL-0242');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Near MD cabin',N'LOC-BL-0243');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_near to Lift',N'LOC-BL-0244');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_North side',N'LOC-BL-0245');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_North Side Ladies rest room',N'LOC-BL-0246');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Office Blue workstations',N'LOC-BL-0247');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Office Green Workstations',N'LOC-BL-0248');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Office Orange Workstations',N'LOC-BL-0249');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_office Rest room',N'LOC-BL-0250');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Office work station_Orange',N'LOC-BL-0251');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Panel room',N'LOC-BL-0252');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Pantry Storage',N'LOC-BL-0253');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Receiption counter',N'LOC-BL-0254');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Receiption to Canteen',N'LOC-BL-0255');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Reception',N'LOC-BL-0256');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Reliability Depart',N'LOC-BL-0257');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_South side',N'LOC-BL-0258');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_South side enterance',N'LOC-BL-0259');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Terrace',N'LOC-BL-0260');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Test Tower',N'LOC-BL-0261');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Test Tower 10th Flr',N'LOC-BL-0262');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Test Tower 17th Flr',N'LOC-BL-0263');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Test Tower 18th Flr',N'LOC-BL-0264');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Test Tower 1st Flr',N'LOC-BL-0265');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Test Tower 20th flr',N'LOC-BL-0266');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Test Tower 7th flr',N'LOC-BL-0267');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Test Tower 9th flr',N'LOC-BL-0268');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Test Tower Basement',N'LOC-BL-0269');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Test Tower G flr',N'LOC-BL-0270');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_wayment bridge',N'LOC-BL-0271');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Weighment room',N'LOC-BL-0272');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-I_Sports room',N'LOC-BL-0273');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Delivery Center_ULDC Warehouse',N'LOC-BL-0274');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Delivery Center_ULDC warehouse QC',N'LOC-BL-0275');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Different locations',N'LOC-BL-0276');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Entire Factory Land lease cost',N'LOC-BL-0277');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Expact',N'LOC-BL-0278');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory &HO_Admin',N'LOC-BL-0279');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory _ Building I & II',N'LOC-BL-0280');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory Building renovation work',N'LOC-BL-0281');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory Fencing',N'LOC-BL-0282');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory&HO_Engineering Depart',N'LOC-BL-0283');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory&HO_IT',N'LOC-BL-0284');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory&HO_Maintenance Depart',N'LOC-BL-0285');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory&HO_Maintenance Room Front',N'LOC-BL-0286');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory&HO_MPL_QC',N'LOC-BL-0287');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory&HO_Purchase Depart',N'LOC-BL-0288');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory&HO_QC',N'LOC-BL-0289');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_200 KVA UPS',N'LOC-BL-0290');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_All compressors areas',N'LOC-BL-0291');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_ASSEMBLEY AREA-2',N'LOC-BL-0292');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_ASSEMBLEY AREA-4',N'LOC-BL-0293');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_ASSEMBLY AREA 1',N'LOC-BL-0294');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_ASSEMBLY AREA 3',N'LOC-BL-0295');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_CAR PARKING 1',N'LOC-BL-0296');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_CAR PARKING 2',N'LOC-BL-0297');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_CO2 LASER MACHINE',N'LOC-BL-0298');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Concrete Weight bridge',N'LOC-BL-0299');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_DG YARD',N'LOC-BL-0300');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_DRIVER REST ROOM FRONT SIDE',N'LOC-BL-0301');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Driver room inside',N'LOC-BL-0302');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Drivers room',N'LOC-BL-0303');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_EPL Qty1no',N'LOC-BL-0304');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_EPL wiring harness',N'LOC-BL-0305');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_FIBER LASER',N'LOC-BL-0306');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Gate 1',N'LOC-BL-0307');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Gate 2',N'LOC-BL-0308');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Gate 3',N'LOC-BL-0309');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_HR & Admin',N'LOC-BL-0310');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_HT YARD GATE',N'LOC-BL-0311');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_HYDRAULIC PRESS BRAKE-1',N'LOC-BL-0312');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_HYDRAULIC PRESS BRAKE-2',N'LOC-BL-0313');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_LPG PLANT-1',N'LOC-BL-0314');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_LPG PLANT-2',N'LOC-BL-0315');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_MPL_CO2 laser Machine',N'LOC-BL-0316');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_O2-N2- GAS PLANT',N'LOC-BL-0317');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_OHC',N'LOC-BL-0318');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PACKING AREA-1',N'LOC-BL-0319');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PACKING AREA-2',N'LOC-BL-0320');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PANAL BONDING MECHINE',N'LOC-BL-0321');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PC',N'LOC-BL-0322');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PC BOOTH_1',N'LOC-BL-0323');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PC BOOTH_2',N'LOC-BL-0324');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PC_ UNLOADING AREA',N'LOC-BL-0325');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PC_LOADING AREA',N'LOC-BL-0326');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PT LINE 1',N'LOC-BL-0327');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PT LINE 2',N'LOC-BL-0328');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PT LINE 3',N'LOC-BL-0329');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Pump room',N'LOC-BL-0330');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PUMP ROOM FRONT SIDE',N'LOC-BL-0331');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_QC',N'LOC-BL-0332');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Quality',N'LOC-BL-0333');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_SALVAGNINI-P4',N'LOC-BL-0334');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_SALVAGNINI-S4',N'LOC-BL-0335');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_SCARP YARD WEST SIDE',N'LOC-BL-0336');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_SCRAP YARD',N'LOC-BL-0337');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Security',N'LOC-BL-0338');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Security room',N'LOC-BL-0339');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Service Warehouse',N'LOC-BL-0340');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_SHEARING MECHINE',N'LOC-BL-0341');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Sheet storage-1',N'LOC-BL-0342');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Sheet storage-2',N'LOC-BL-0343');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Showroom entry',N'LOC-BL-0344');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Showroom Lift',N'LOC-BL-0345');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Showroom seating area',N'LOC-BL-0346');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_TURRET PUNCHING-1',N'LOC-BL-0347');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_TURRET PUNCHING-2',N'LOC-BL-0348');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_warehouse 2nos& Building-1_Housekeeping ro',N'LOC-BL-0349');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Warehouse loading/Receiving',N'LOC-BL-0350');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Warehouse office',N'LOC-BL-0351');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Warehouse1nos&MPL-2nos',N'LOC-BL-0352');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_WELDDING',N'LOC-BL-0353');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'HO_Corporate Planning',N'LOC-BL-0354');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'HO_IT Server Room',N'LOC-BL-0355');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Locker Room',N'LOC-BL-0356');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Main Gate',N'LOC-BL-0357');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'MPL_Factory & EPL_Factory',N'LOC-BL-0358');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Next to Factory Electrial Room',N'LOC-BL-0359');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Next to Pupm room',N'LOC-BL-0360');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'North Security room 1',N'LOC-BL-0361');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Purchase Wing',N'LOC-BL-0362');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'South security room 2',N'LOC-BL-0363');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Vendor_Inovance Technology Pvt Ltd',N'LOC-BL-0364');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Weight bridge_ Factory',N'LOC-BL-0365');
INSERT @Locations VALUES (N'Fujitec Goa',N'Goa_Install',N'LOC-BL-0366');
INSERT @Locations VALUES (N'Fujitec Goa',N'Goa_IT',N'LOC-BL-0367');
INSERT @Locations VALUES (N'Fujitec Goa',N'Goa_Office',N'LOC-BL-0368');
INSERT @Locations VALUES (N'Fujitec Goa',N'Goa_Sales',N'LOC-BL-0369');
INSERT @Locations VALUES (N'Fujitec Haryana-1',N'Factory&HO_IT',N'LOC-BL-0370');
INSERT @Locations VALUES (N'Fujitec Haryana-1',N'Haryana-1_IT',N'LOC-BL-0371');
INSERT @Locations VALUES (N'Fujitec Haryana-1',N'Haryana1_Admin',N'LOC-BL-0372');
INSERT @Locations VALUES (N'Fujitec Haryana-1',N'Haryana1_Install',N'LOC-BL-0373');
INSERT @Locations VALUES (N'Fujitec Haryana-1',N'Haryana1_IT',N'LOC-BL-0374');
INSERT @Locations VALUES (N'Fujitec Haryana-1',N'Haryana1_Office',N'LOC-BL-0375');
INSERT @Locations VALUES (N'Fujitec Haryana-1',N'Haryana1_Sales',N'LOC-BL-0376');
INSERT @Locations VALUES (N'Fujitec Haryana-1',N'Haryana1_Service',N'LOC-BL-0377');
INSERT @Locations VALUES (N'Fujitec Haryana-1',N'Haryana_IT',N'LOC-BL-0378');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Bangalore-IT',N'LOC-BL-0379');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Factory&HO_IT',N'LOC-BL-0380');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderabad _Region HO',N'LOC-BL-0381');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderabad_Admin',N'LOC-BL-0382');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderabad_Install',N'LOC-BL-0383');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderabad_IT',N'LOC-BL-0384');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderabad_Office',N'LOC-BL-0385');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderabad_Safety',N'LOC-BL-0386');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderabad_sales',N'LOC-BL-0387');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderabad_saless',N'LOC-BL-0388');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderabad_Service',N'LOC-BL-0389');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderabad_Warehouse',N'LOC-BL-0390');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderadad_Br Manager',N'LOC-BL-0391');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderadad_IT',N'LOC-BL-0392');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'1no Maintrn room &2nos Southside security',N'LOC-BL-0393');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'1no Security Room & 2-Maint Dept Rooom',N'LOC-BL-0394');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Admin&HR_HO',N'LOC-BL-0395');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Bangalore_IT',N'LOC-BL-0396');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Between Building_1 & Building-2',N'LOC-BL-0397');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1',N'LOC-BL-0398');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1 network cables',N'LOC-BL-0399');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1st  flr_southwing',N'LOC-BL-0400');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1st Flr Cabin 25 Lilac',N'LOC-BL-0401');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1st Flr IT store',N'LOC-BL-0402');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1st flr Northwing',N'LOC-BL-0403');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1st flr Northwing Green',N'LOC-BL-0404');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1st Flr Record rood 1',N'LOC-BL-0405');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1st Flr Southwing Workstations',N'LOC-BL-0406');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1st Flr_30 Morning Glory',N'LOC-BL-0407');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1st flr_Northwing',N'LOC-BL-0408');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1st flr_SouthWing',N'LOC-BL-0409');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1stfloor Training center',N'LOC-BL-0410');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1stFlr 29 Jasmine',N'LOC-BL-0411');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1stFlr_24 Buttercups',N'LOC-BL-0412');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Customer Experience Center',N'LOC-BL-0413');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_EPT Plant',N'LOC-BL-0414');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Experience Centre',N'LOC-BL-0415');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Finance_Department',N'LOC-BL-0416');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Fince Rrd room 3nos& IT-store4nos',N'LOC-BL-0417');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_G & 1st Floor',N'LOC-BL-0418');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_G Flr cabin 31 Alfalfa',N'LOC-BL-0419');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_G flr Conference room',N'LOC-BL-0420');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_G flr_Northwing',N'LOC-BL-0421');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Gfloolr Maint Depart Room',N'LOC-BL-0422');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Gfloor north wing_Near to Cabin31',N'LOC-BL-0423');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_HO_admin',N'LOC-BL-0424');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_House keeping Room',N'LOC-BL-0425');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_IT Server room',N'LOC-BL-0426');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Maintenance Depart',N'LOC-BL-0427');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_MPL',N'LOC-BL-0428');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_PCP',N'LOC-BL-0429');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_PCP near',N'LOC-BL-0430');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Quality Hall',N'LOC-BL-0431');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Receiption',N'LOC-BL-0432');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Receiption area',N'LOC-BL-0433');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_RMS Room',N'LOC-BL-0434');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Stationery room',N'LOC-BL-0435');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Terrace',N'LOC-BL-0436');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Test Tower',N'LOC-BL-0437');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Training center',N'LOC-BL-0438');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2 cabin 5 Pansy1nos& Quality hall 1nos',N'LOC-BL-0439');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2 canteen & Security Gate-1 store room',N'LOC-BL-0440');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_ IT Server room',N'LOC-BL-0441');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Business support Depart',N'LOC-BL-0442');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_cabin 1 Rudrapushpa',N'LOC-BL-0443');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_cabin 13 Tulip',N'LOC-BL-0444');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_cabin 15 Lavender',N'LOC-BL-0445');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_cabin 17 Orchid',N'LOC-BL-0446');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_cabin 4 Ashok',N'LOC-BL-0447');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_cabin 5 Pansy',N'LOC-BL-0448');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_cabin 6 Dahlia',N'LOC-BL-0449');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_cabin 7 Navmallika',N'LOC-BL-0450');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_cabin 8 Neel Kamal',N'LOC-BL-0451');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_cabin 9 Champakam',N'LOC-BL-0452');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Canteen',N'LOC-BL-0453');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_EPL',N'LOC-BL-0454');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Factory_warehouse',N'LOC-BL-0455');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Pantry room',N'LOC-BL-0456');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Reception',N'LOC-BL-0457');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Reception.',N'LOC-BL-0458');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Reliability Depart',N'LOC-BL-0459');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Server room',N'LOC-BL-0460');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Test Tower',N'LOC-BL-0461');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Test Tower 18th Flr',N'LOC-BL-0462');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Test Tower Basement',N'LOC-BL-0463');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Vendor Developer',N'LOC-BL-0464');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Chennai_Install',N'LOC-BL-0465');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'CHQ_IT',N'LOC-BL-0466');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'CHQ_Server',N'LOC-BL-0467');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'CMRL_IT',N'LOC-BL-0468');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Different locations',N'LOC-BL-0469');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory Location',N'LOC-BL-0470');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory&HO_Engineering Depart',N'LOC-BL-0471');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory&HO_IT',N'LOC-BL-0472');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory&HO_Maintenance Depart',N'LOC-BL-0473');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory&HO_Parking_MD',N'LOC-BL-0474');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory&HO_Purchase Depart',N'LOC-BL-0475');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory&HO_QC',N'LOC-BL-0476');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory_EPL&Engg',N'LOC-BL-0477');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory_HOD',N'LOC-BL-0478');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory_Maitenance',N'LOC-BL-0479');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory_MPL',N'LOC-BL-0480');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory_PC',N'LOC-BL-0481');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory_Planning Depart',N'LOC-BL-0482');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory_warehouse Maintenance',N'LOC-BL-0483');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory_Warehouse2ns, Housekeepingroom3nos,EPL2nos',N'LOC-BL-0484');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Fujitec India_Admin',N'LOC-BL-0485');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Fujitec_HO',N'LOC-BL-0486');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'HO_Admin&HR',N'LOC-BL-0487');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'HO_Corporate Planning',N'LOC-BL-0488');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'HO_Finance',N'LOC-BL-0489');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'HO_FOD Install Depart',N'LOC-BL-0490');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'HO_HR Office Chennai',N'LOC-BL-0491');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'HO_IT Server Room',N'LOC-BL-0492');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'HO_Operation',N'LOC-BL-0493');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'HO_Product development',N'LOC-BL-0494');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'HO_Project Engineering',N'LOC-BL-0495');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'HO_Service',N'LOC-BL-0496');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'HR Department',N'LOC-BL-0497');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Mumbai',N'LOC-BL-0498');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Mumbai-1',N'LOC-BL-0499');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'North Security room 1',N'LOC-BL-0500');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'PUne',N'LOC-BL-0501');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'PUne_Install',N'LOC-BL-0502');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'South Security room 2',N'LOC-BL-0503');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Vehicle Parking area',N'LOC-BL-0504');
INSERT @Locations VALUES (N'Fujitec Jaipur',N'Factory&HO_IT',N'LOC-BL-0505');
INSERT @Locations VALUES (N'Fujitec Jaipur',N'Jaipur_Install',N'LOC-BL-0506');
INSERT @Locations VALUES (N'Fujitec Jaipur',N'Jaipur_IT',N'LOC-BL-0507');
INSERT @Locations VALUES (N'Fujitec Jaipur',N'Jaipur_Office',N'LOC-BL-0508');
INSERT @Locations VALUES (N'Fujitec Jaipur',N'Jaipur_Sales',N'LOC-BL-0509');
INSERT @Locations VALUES (N'Fujitec Kolkata',N'Factory&HO_IT',N'LOC-BL-0510');
INSERT @Locations VALUES (N'Fujitec Kolkata',N'Haryana-1_IT',N'LOC-BL-0511');
INSERT @Locations VALUES (N'Fujitec Kolkata',N'Kolkata_Install',N'LOC-BL-0512');
INSERT @Locations VALUES (N'Fujitec Kolkata',N'Kolkata_IT',N'LOC-BL-0513');
INSERT @Locations VALUES (N'Fujitec Kolkata',N'Kolkata_Office',N'LOC-BL-0514');
INSERT @Locations VALUES (N'Fujitec Kolkata',N'Kolkata_Service',N'LOC-BL-0515');
INSERT @Locations VALUES (N'Fujitec Mumbai1',N'Factory&HO_IT',N'LOC-BL-0516');
INSERT @Locations VALUES (N'Fujitec Mumbai1',N'Mumbai-1_IT',N'LOC-BL-0517');
INSERT @Locations VALUES (N'Fujitec Mumbai1',N'Mumbai1_Admin',N'LOC-BL-0518');
INSERT @Locations VALUES (N'Fujitec Mumbai1',N'Mumbai1_HR',N'LOC-BL-0519');
INSERT @Locations VALUES (N'Fujitec Mumbai1',N'Mumbai1_Install',N'LOC-BL-0520');
INSERT @Locations VALUES (N'Fujitec Mumbai1',N'Mumbai1_IT',N'LOC-BL-0521');
INSERT @Locations VALUES (N'Fujitec Mumbai1',N'Mumbai1_Manager',N'LOC-BL-0522');
INSERT @Locations VALUES (N'Fujitec Mumbai1',N'Mumbai1_Office',N'LOC-BL-0523');
INSERT @Locations VALUES (N'Fujitec Mumbai1',N'Mumbai1_safety',N'LOC-BL-0524');
INSERT @Locations VALUES (N'Fujitec Mumbai1',N'Mumbai1_Sales',N'LOC-BL-0525');
INSERT @Locations VALUES (N'Fujitec Mumbai1',N'Mumbai1_Service',N'LOC-BL-0526');
INSERT @Locations VALUES (N'Fujitec Mumbai2',N'Factory&HO_IT',N'LOC-BL-0527');
INSERT @Locations VALUES (N'Fujitec Mumbai2',N'Haryana-1_IT',N'LOC-BL-0528');
INSERT @Locations VALUES (N'Fujitec Mumbai2',N'Mumbai-2_Install',N'LOC-BL-0529');
INSERT @Locations VALUES (N'Fujitec Mumbai2',N'Mumbai-2_IT',N'LOC-BL-0530');
INSERT @Locations VALUES (N'Fujitec Mumbai2',N'Mumbai2_Install',N'LOC-BL-0531');
INSERT @Locations VALUES (N'Fujitec Mumbai2',N'Mumbai2_IT',N'LOC-BL-0532');
INSERT @Locations VALUES (N'Fujitec Mumbai2',N'Mumbai2_Office',N'LOC-BL-0533');
INSERT @Locations VALUES (N'Fujitec Mumbai3 (NVM)',N'Mumbai3_Admin',N'LOC-BL-0534');
INSERT @Locations VALUES (N'Fujitec Mumbai3 (NVM)',N'Mumbai3_Finance',N'LOC-BL-0535');
INSERT @Locations VALUES (N'Fujitec Mumbai3 (NVM)',N'Mumbai3_Install',N'LOC-BL-0536');
INSERT @Locations VALUES (N'Fujitec Mumbai3 (NVM)',N'Mumbai3_IT',N'LOC-BL-0537');
INSERT @Locations VALUES (N'Fujitec Mumbai3 (NVM)',N'Mumbai3_Offfice',N'LOC-BL-0538');
INSERT @Locations VALUES (N'Fujitec Mumbai3 (NVM)',N'Mumbai3_Safety',N'LOC-BL-0539');
INSERT @Locations VALUES (N'Fujitec Mumbai3 (NVM)',N'Mumbai3_Sales',N'LOC-BL-0540');
INSERT @Locations VALUES (N'Fujitec Mumbai3 (NVM)',N'Mumbai3_Service',N'LOC-BL-0541');
INSERT @Locations VALUES (N'Fujitec NIB Head Office',N'Engg_NIB Head office',N'LOC-BL-0542');
INSERT @Locations VALUES (N'Fujitec NIB Head Office',N'Factory&HO_IT',N'LOC-BL-0543');
INSERT @Locations VALUES (N'Fujitec NIB Head Office',N'NIB Head office_Install',N'LOC-BL-0544');
INSERT @Locations VALUES (N'Fujitec NIB Head Office',N'NIB Head office_IT',N'LOC-BL-0545');
INSERT @Locations VALUES (N'Fujitec NIB Head Office',N'NIB Head Office_Manager',N'LOC-BL-0546');
INSERT @Locations VALUES (N'Fujitec NIB Head Office',N'NIB Head Office_Office',N'LOC-BL-0547');
INSERT @Locations VALUES (N'Fujitec NIB Head Office',N'NIB Head office_Operations',N'LOC-BL-0548');
INSERT @Locations VALUES (N'Fujitec NIB Head Office',N'NIB Head office_Sales',N'LOC-BL-0549');
INSERT @Locations VALUES (N'Fujitec Odisha',N'Odisha_IT',N'LOC-BL-0550');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Factory&HO_IT',N'LOC-BL-0551');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Pune-1_Install',N'LOC-BL-0552');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Pune-1_IT',N'LOC-BL-0553');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Pune1_ Office',N'LOC-BL-0554');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Pune1_Admin',N'LOC-BL-0555');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Pune1_Finance',N'LOC-BL-0556');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Pune1_Install',N'LOC-BL-0557');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Pune1_IT',N'LOC-BL-0558');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Pune1_Office',N'LOC-BL-0559');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Pune1_Quality',N'LOC-BL-0560');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Pune1_Sales',N'LOC-BL-0561');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Pune1_Service',N'LOC-BL-0562');
INSERT @Locations VALUES (N'Fujitec Punjab',N'Chandigarh_IT',N'LOC-BL-0563');
INSERT @Locations VALUES (N'Fujitec Punjab',N'Punjab-Install',N'LOC-BL-0564');
INSERT @Locations VALUES (N'Fujitec Punjab',N'Punjab_HR',N'LOC-BL-0565');
INSERT @Locations VALUES (N'Fujitec Punjab',N'Punjab_Install',N'LOC-BL-0566');
INSERT @Locations VALUES (N'Fujitec Punjab',N'Punjab_IT',N'LOC-BL-0567');
INSERT @Locations VALUES (N'Fujitec Punjab',N'Punjab_Office',N'LOC-BL-0568');
INSERT @Locations VALUES (N'Fujitec Punjab',N'Punjab_Safety',N'LOC-BL-0569');
INSERT @Locations VALUES (N'Fujitec Punjab',N'Punjab_Sales',N'LOC-BL-0570');
INSERT @Locations VALUES (N'Fujitec Punjab',N'Punjab_Service',N'LOC-BL-0571');
INSERT @Locations VALUES (N'Fujitec Uttar Pradesh',N'HO_FOD Install Depart',N'LOC-BL-0572');
INSERT @Locations VALUES (N'Fujitec Uttar Pradesh',N'Uttar Pradesh',N'LOC-BL-0573');
INSERT @Locations VALUES (N'Fujitec Uttar Pradesh',N'Uttar Pradesh_Admin',N'LOC-BL-0574');
INSERT @Locations VALUES (N'Fujitec Uttar Pradesh',N'Uttar Pradesh_Finance',N'LOC-BL-0575');
INSERT @Locations VALUES (N'Fujitec Uttar Pradesh',N'Uttar Pradesh_Install',N'LOC-BL-0576');
INSERT @Locations VALUES (N'Fujitec Uttar Pradesh',N'Uttar Pradesh_IT',N'LOC-BL-0577');
INSERT @Locations VALUES (N'Fujitec Uttar Pradesh',N'Uttar Pradesh_Lucknow',N'LOC-BL-0578');
INSERT @Locations VALUES (N'Fujitec Uttar Pradesh',N'Uttar Pradesh_Office',N'LOC-BL-0579');
INSERT @Locations VALUES (N'Fujitec Uttar Pradesh',N'Uttar Pradesh_Sales',N'LOC-BL-0580');
INSERT @Locations VALUES (N'Fujitec Uttar Pradesh',N'Uttar Pradesh_Service',N'LOC-BL-0581');
IF EXISTS(SELECT 1 FROM @Locations l LEFT JOIN [Identity].[OrganizationUnit] b ON b.OrganizationId=@OrganizationId AND b.UnitType=N'Branch' AND b.UnitName=l.BranchName AND b.IsActive=1 WHERE b.OrganizationUnitId IS NULL) THROW 51002, 'A workbook Branch is missing from IAM.', 1;
DELETE actual FROM [Identity].[OrganizationUnit] actual JOIN [Identity].[OrganizationUnit] b ON b.OrganizationUnitId=actual.ParentOrganizationUnitId WHERE actual.OrganizationId=@OrganizationId AND actual.UnitType=N'Location' AND actual.UnitCode LIKE N'LOC-ASSET-%' AND NOT EXISTS(SELECT 1 FROM @Locations expected WHERE expected.BranchName=b.UnitName AND expected.LocationName=actual.UnitName);
UPDATE actual SET UnitName=expected.LocationName,UpdatedAt=SYSUTCDATETIME() FROM [Identity].[OrganizationUnit] actual JOIN [Identity].[OrganizationUnit] b ON b.OrganizationUnitId=actual.ParentOrganizationUnitId JOIN @Locations expected ON expected.BranchName=b.UnitName AND expected.LocationName=actual.UnitName WHERE actual.OrganizationId=@OrganizationId AND actual.UnitType=N'Location' AND actual.UnitName COLLATE Latin1_General_100_BIN2 <> expected.LocationName COLLATE Latin1_General_100_BIN2;
INSERT INTO [Identity].[OrganizationUnit](OrganizationId,ParentOrganizationUnitId,UnitType,UnitCode,UnitName,IsActive,CreatedAt,UpdatedAt) SELECT @OrganizationId,b.OrganizationUnitId,N'Location',l.LocationCode,l.LocationName,1,SYSUTCDATETIME(),SYSUTCDATETIME() FROM @Locations l JOIN [Identity].[OrganizationUnit] b ON b.OrganizationId=@OrganizationId AND b.UnitType=N'Branch' AND b.UnitName=l.BranchName AND b.IsActive=1 WHERE NOT EXISTS(SELECT 1 FROM [Identity].[OrganizationUnit] existing WHERE existing.OrganizationId=@OrganizationId AND existing.UnitType=N'Location' AND existing.ParentOrganizationUnitId=b.OrganizationUnitId AND existing.UnitName=l.LocationName);
UPDATE u SET HierarchyPath=p.HierarchyPath+CONVERT(nvarchar(20),u.OrganizationUnitId)+N'/' FROM [Identity].[OrganizationUnit] u JOIN [Identity].[OrganizationUnit] p ON p.OrganizationUnitId=u.ParentOrganizationUnitId WHERE u.OrganizationId=@OrganizationId AND u.UnitType=N'Location' AND u.HierarchyPath IS NULL;
IF EXISTS(SELECT 1 FROM @Locations l JOIN [Identity].[OrganizationUnit] b ON b.OrganizationId=@OrganizationId AND b.UnitType=N'Branch' AND b.UnitName=l.BranchName LEFT JOIN [Identity].[OrganizationUnit] actual ON actual.OrganizationId=@OrganizationId AND actual.UnitType=N'Location' AND actual.ParentOrganizationUnitId=b.OrganizationUnitId AND actual.UnitName=l.LocationName WHERE actual.OrganizationUnitId IS NULL) THROW 51004, 'A workbook mapping is missing after import.', 1;
IF EXISTS(SELECT 1 FROM [Identity].[OrganizationUnit] actual JOIN [Identity].[OrganizationUnit] b ON b.OrganizationUnitId=actual.ParentOrganizationUnitId WHERE actual.OrganizationId=@OrganizationId AND actual.UnitType=N'Location' AND actual.UnitCode LIKE N'LOC-ASSET-%' AND NOT EXISTS(SELECT 1 FROM @Locations expected WHERE expected.BranchName=b.UnitName AND expected.LocationName=actual.UnitName)) THROW 51005, 'An unexpected imported mapping remains.', 1;
COMMIT;
SELECT COUNT(DISTINCT b.OrganizationUnitId) AS ImportedBranches, COUNT(*) AS VerifiedWorkbookMappings, COUNT(DISTINCT expected.LocationName) AS DistinctLocationNames FROM @Locations expected JOIN [Identity].[OrganizationUnit] b ON b.OrganizationId=@OrganizationId AND b.UnitType=N'Branch' AND b.UnitName=expected.BranchName JOIN [Identity].[OrganizationUnit] actual ON actual.OrganizationId=@OrganizationId AND actual.UnitType=N'Location' AND actual.ParentOrganizationUnitId=b.OrganizationUnitId AND actual.UnitName=expected.LocationName;
