USE [IAM_LocalTest];
GO
SET ANSI_NULLS ON; SET QUOTED_IDENTIFIER ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET CONCAT_NULL_YIELDS_NULL ON; SET ARITHABORT ON; SET NUMERIC_ROUNDABORT OFF; SET NOCOUNT ON; SET XACT_ABORT ON;
IF DB_NAME() <> N'IAM_LocalTest' THROW 51000, 'Wrong database selected.', 1;
BEGIN TRANSACTION;
DECLARE @OrganizationId bigint = (SELECT OrganizationId FROM [Identity].[OrganizationUnit] WHERE UnitType=N'Organization' AND UnitName=N'AMS Test Organization' AND IsActive=1);
DECLARE @CountryId bigint = (SELECT OrganizationUnitId FROM [Identity].[OrganizationUnit] WHERE OrganizationId=@OrganizationId AND UnitType=N'Country' AND UnitName=N'India' AND IsActive=1);
IF @OrganizationId IS NULL OR @CountryId IS NULL THROW 51001, 'AMS Test Organization / India was not found.', 1;
DECLARE @Regions TABLE(Name nvarchar(400), Code nvarchar(100));
INSERT @Regions VALUES (N'East Test Region', N'REG-TEST-01');
INSERT @Regions VALUES (N'North Test Region', N'REG-TEST-02');
INSERT @Regions VALUES (N'South Test Region', N'REG-TEST-03');
INSERT @Regions VALUES (N'West Test Region', N'REG-TEST-04');
DELETE FROM @Regions WHERE Name=N'South Test Region';
INSERT INTO [Identity].[OrganizationUnit](OrganizationId,ParentOrganizationUnitId,UnitType,UnitCode,UnitName,IsActive,CreatedAt,UpdatedAt) SELECT @OrganizationId,@CountryId,N'Region',r.Code,r.Name,1,SYSUTCDATETIME(),SYSUTCDATETIME() FROM @Regions r WHERE NOT EXISTS(SELECT 1 FROM [Identity].[OrganizationUnit] u WHERE u.OrganizationId=@OrganizationId AND u.UnitType=N'Region' AND u.UnitName=r.Name);
UPDATE u SET HierarchyPath=p.HierarchyPath+CONVERT(nvarchar(20),u.OrganizationUnitId)+N'/' FROM [Identity].[OrganizationUnit] u JOIN [Identity].[OrganizationUnit] p ON p.OrganizationUnitId=u.ParentOrganizationUnitId WHERE u.OrganizationId=@OrganizationId AND u.UnitType=N'Region' AND u.HierarchyPath IS NULL;
DECLARE @States TABLE(Name nvarchar(400), RegionName nvarchar(400), Code nvarchar(100));
INSERT @States VALUES (N'Telangana',N'South Test Region',N'ST-TEST-01');
INSERT @States VALUES (N'Karnataka',N'South Test Region',N'ST-TEST-02');
INSERT @States VALUES (N'Kerala',N'South Test Region',N'ST-TEST-03');
INSERT @States VALUES (N'Andhra Pradesh',N'South Test Region',N'ST-TEST-04');
INSERT @States VALUES (N'Uttar Pradesh',N'North Test Region',N'ST-TEST-05');
INSERT @States VALUES (N'Haryana',N'North Test Region',N'ST-TEST-06');
INSERT @States VALUES (N'Delhi',N'North Test Region',N'ST-TEST-07');
INSERT @States VALUES (N'Punjab',N'North Test Region',N'ST-TEST-08');
INSERT @States VALUES (N'Rajasthan',N'North Test Region',N'ST-TEST-09');
INSERT @States VALUES (N'Maharashtra',N'West Test Region',N'ST-TEST-10');
INSERT @States VALUES (N'Goa',N'West Test Region',N'ST-TEST-11');
INSERT @States VALUES (N'Gujarat',N'West Test Region',N'ST-TEST-12');
INSERT @States VALUES (N'West Bengal',N'East Test Region',N'ST-TEST-13');
INSERT @States VALUES (N'Odisha',N'East Test Region',N'ST-TEST-14');
INSERT INTO [Identity].[OrganizationUnit](OrganizationId,ParentOrganizationUnitId,UnitType,UnitCode,UnitName,IsActive,CreatedAt,UpdatedAt) SELECT @OrganizationId,r.OrganizationUnitId,N'State',s.Code,s.Name,1,SYSUTCDATETIME(),SYSUTCDATETIME() FROM @States s JOIN [Identity].[OrganizationUnit] r ON r.OrganizationId=@OrganizationId AND r.UnitType=N'Region' AND r.UnitName=s.RegionName WHERE NOT EXISTS(SELECT 1 FROM [Identity].[OrganizationUnit] u WHERE u.OrganizationId=@OrganizationId AND u.UnitType=N'State' AND u.UnitName=s.Name);
UPDATE u SET HierarchyPath=p.HierarchyPath+CONVERT(nvarchar(20),u.OrganizationUnitId)+N'/' FROM [Identity].[OrganizationUnit] u JOIN [Identity].[OrganizationUnit] p ON p.OrganizationUnitId=u.ParentOrganizationUnitId WHERE u.OrganizationId=@OrganizationId AND u.UnitType=N'State' AND u.HierarchyPath IS NULL;
DECLARE @Branches TABLE(Name nvarchar(400), StateName nvarchar(400), Code nvarchar(100));
INSERT @Branches VALUES (N'Central Service Warehouse',N'Tamil Nadu Test',N'BR-ASSET-001');
INSERT @Branches VALUES (N'Delivery Center',N'Tamil Nadu Test',N'BR-ASSET-002');
INSERT @Branches VALUES (N'Fujitec Ahmedabad',N'Gujarat',N'BR-ASSET-003');
INSERT @Branches VALUES (N'Fujitec Andhra Pradesh',N'Andhra Pradesh',N'BR-ASSET-004');
INSERT @Branches VALUES (N'Fujitec Bangalore',N'Karnataka',N'BR-ASSET-005');
INSERT @Branches VALUES (N'Fujitec Chennai',N'Tamil Nadu Test',N'BR-ASSET-006');
INSERT @Branches VALUES (N'Fujitec CMRL',N'Tamil Nadu Test',N'BR-ASSET-007');
INSERT @Branches VALUES (N'Fujitec Cochin',N'Kerala',N'BR-ASSET-008');
INSERT @Branches VALUES (N'Fujitec Delhi',N'Delhi',N'BR-ASSET-009');
INSERT @Branches VALUES (N'Fujitec Factory Office',N'Tamil Nadu Test',N'BR-ASSET-010');
INSERT @Branches VALUES (N'Fujitec Goa',N'Goa',N'BR-ASSET-011');
INSERT @Branches VALUES (N'Fujitec Haryana-1',N'Haryana',N'BR-ASSET-012');
INSERT @Branches VALUES (N'Fujitec Hyderabad',N'Telangana',N'BR-ASSET-013');
INSERT @Branches VALUES (N'Fujitec India Pvt Ltd',N'Tamil Nadu Test',N'BR-ASSET-014');
INSERT @Branches VALUES (N'Fujitec Jaipur',N'Rajasthan',N'BR-ASSET-015');
INSERT @Branches VALUES (N'Fujitec Kolkata',N'West Bengal',N'BR-ASSET-016');
INSERT @Branches VALUES (N'Fujitec Mumbai1',N'Maharashtra',N'BR-ASSET-017');
INSERT @Branches VALUES (N'Fujitec Mumbai2',N'Maharashtra',N'BR-ASSET-018');
INSERT @Branches VALUES (N'Fujitec Mumbai3 (NVM)',N'Maharashtra',N'BR-ASSET-019');
INSERT @Branches VALUES (N'Fujitec NIB Head Office',N'Tamil Nadu Test',N'BR-ASSET-020');
INSERT @Branches VALUES (N'Fujitec Odisha',N'Odisha',N'BR-ASSET-021');
INSERT @Branches VALUES (N'Fujitec Pune-1',N'Maharashtra',N'BR-ASSET-022');
INSERT @Branches VALUES (N'Fujitec Punjab',N'Punjab',N'BR-ASSET-023');
INSERT @Branches VALUES (N'Fujitec Uttar Pradesh',N'Uttar Pradesh',N'BR-ASSET-024');
INSERT INTO [Identity].[OrganizationUnit](OrganizationId,ParentOrganizationUnitId,UnitType,UnitCode,UnitName,IsActive,CreatedAt,UpdatedAt) SELECT @OrganizationId,s.OrganizationUnitId,N'Branch',b.Code,b.Name,1,SYSUTCDATETIME(),SYSUTCDATETIME() FROM @Branches b JOIN [Identity].[OrganizationUnit] s ON s.OrganizationId=@OrganizationId AND s.UnitType=N'State' AND s.UnitName=b.StateName WHERE NOT EXISTS(SELECT 1 FROM [Identity].[OrganizationUnit] u WHERE u.OrganizationId=@OrganizationId AND u.UnitType=N'Branch' AND u.ParentOrganizationUnitId=s.OrganizationUnitId AND u.UnitName=b.Name);
UPDATE u SET HierarchyPath=p.HierarchyPath+CONVERT(nvarchar(20),u.OrganizationUnitId)+N'/' FROM [Identity].[OrganizationUnit] u JOIN [Identity].[OrganizationUnit] p ON p.OrganizationUnitId=u.ParentOrganizationUnitId WHERE u.OrganizationId=@OrganizationId AND u.UnitType=N'Branch' AND u.HierarchyPath IS NULL;
DECLARE @Locations TABLE(BranchName nvarchar(400), Name nvarchar(400), Code nvarchar(100));
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Customer Experience Center',N'LOC-ASSET-0001');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory&HO_Maintenance Depart',N'LOC-ASSET-0002');
INSERT @Locations VALUES (N'Fujitec Uttar Pradesh',N'Uttar Pradesh_Install',N'LOC-ASSET-0003');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_EPL',N'LOC-ASSET-0004');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_MWC warehouse',N'LOC-ASSET-0005');
INSERT @Locations VALUES (N'Central Service Warehouse',N'Central Service WH_Chennai',N'LOC-ASSET-0006');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Pune1_Install',N'LOC-ASSET-0007');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_MPL',N'LOC-ASSET-0008');
INSERT @Locations VALUES (N'Fujitec Mumbai1',N'Mumbai1_Install',N'LOC-ASSET-0009');
INSERT @Locations VALUES (N'Fujitec Uttar Pradesh',N'Uttar Pradesh_Service',N'LOC-ASSET-0010');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory&HO_QC',N'LOC-ASSET-0011');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderabad_Service',N'LOC-ASSET-0012');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Pune1_Service',N'LOC-ASSET-0013');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Training center',N'LOC-ASSET-0014');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory Fencing',N'LOC-ASSET-0015');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'HO_IT Server Room',N'LOC-ASSET-0016');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_EPL Warehouse',N'LOC-ASSET-0017');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Chennai_Install',N'LOC-ASSET-0018');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Chennai_Service',N'LOC-ASSET-0019');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Bangalore_Install',N'LOC-ASSET-0020');
INSERT @Locations VALUES (N'Fujitec Mumbai3 (NVM)',N'Mumbai3_Service',N'LOC-ASSET-0021');
INSERT @Locations VALUES (N'Fujitec Cochin',N'Cochin_Install',N'LOC-ASSET-0022');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Floor_Canteen',N'LOC-ASSET-0023');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderabad_Install',N'LOC-ASSET-0024');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Bangalore_Service',N'LOC-ASSET-0025');
INSERT @Locations VALUES (N'Fujitec Haryana-1',N'Haryana1_Install',N'LOC-ASSET-0026');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_G flr Conference room',N'LOC-ASSET-0027');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Bangalore_Admin',N'LOC-ASSET-0028');
INSERT @Locations VALUES (N'Fujitec Mumbai3 (NVM)',N'Mumbai3_Admin',N'LOC-ASSET-0029');
INSERT @Locations VALUES (N'Fujitec Haryana-1',N'Haryana1_Admin',N'LOC-ASSET-0030');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Reliability Depart',N'LOC-ASSET-0031');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory&HO_IT',N'LOC-ASSET-0032');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Receiption area',N'LOC-ASSET-0033');
INSERT @Locations VALUES (N'Fujitec Mumbai1',N'Mumbai1_Admin',N'LOC-ASSET-0034');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Factory_HOD',N'LOC-ASSET-0035');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Gfloolr Maint Depart Room',N'LOC-ASSET-0036');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Factory_warehouse',N'LOC-ASSET-0037');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_IT Server room',N'LOC-ASSET-0038');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1st Flr Record rood 1',N'LOC-ASSET-0039');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G Flr cabin 31 Alfalfa',N'LOC-ASSET-0040');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Mumbai1_Service',N'LOC-ASSET-0041');
INSERT @Locations VALUES (N'Fujitec Uttar Pradesh',N'Uttar Pradesh_Admin',N'LOC-ASSET-0042');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Experience Centre',N'LOC-ASSET-0043');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'HO_Project Engineering',N'LOC-ASSET-0044');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_ IT Server room',N'LOC-ASSET-0045');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Factory_warehouse',N'LOC-ASSET-0046');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'1no Maintrn room &2nos Southside security',N'LOC-ASSET-0047');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_House keeping Room',N'LOC-ASSET-0048');
INSERT @Locations VALUES (N'Fujitec Haryana-1',N'Haryana1_Office',N'LOC-ASSET-0049');
INSERT @Locations VALUES (N'Fujitec Mumbai1',N'Mumbai1_Service',N'LOC-ASSET-0050');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Quality Hall',N'LOC-ASSET-0051');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Chennai_Admin',N'LOC-ASSET-0052');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_EPL',N'LOC-ASSET-0053');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'HO_FOD Install Depart',N'LOC-ASSET-0054');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_G & 1st Floor',N'LOC-ASSET-0055');
INSERT @Locations VALUES (N'Fujitec Mumbai3 (NVM)',N'Mumbai3_IT',N'LOC-ASSET-0056');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_MPL',N'LOC-ASSET-0057');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Bangalore_IT',N'LOC-ASSET-0058');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Chennai_Br Manager',N'LOC-ASSET-0059');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'HO_Corporate Planning',N'LOC-ASSET-0060');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_PCP',N'LOC-ASSET-0061');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory&HO_MPL_QC',N'LOC-ASSET-0062');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_MPL 1nos& Dry Pantry1nos',N'LOC-ASSET-0063');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_EPL Qty1no',N'LOC-ASSET-0064');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Pantry room',N'LOC-ASSET-0065');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_warehouse 2nos& Building-1_Housekeeping ro',N'LOC-ASSET-0066');
INSERT @Locations VALUES (N'Fujitec Haryana-1',N'Haryana1_IT',N'LOC-ASSET-0067');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Pune1_IT',N'LOC-ASSET-0068');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'HO_Product development',N'LOC-ASSET-0069');
INSERT @Locations VALUES (N'Fujitec Delhi',N'Delhi_IT',N'LOC-ASSET-0070');
INSERT @Locations VALUES (N'Delivery Center',N'Delivery Center_ULDC Warehouse',N'LOC-ASSET-0071');
INSERT @Locations VALUES (N'Fujitec Mumbai1',N'Mumbai1_Manager',N'LOC-ASSET-0072');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'HO_Finance',N'LOC-ASSET-0073');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderabad_saless',N'LOC-ASSET-0074');
INSERT @Locations VALUES (N'Fujitec Mumbai3 (NVM)',N'Mumbai3_Sales',N'LOC-ASSET-0075');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory&HO_Parking_MD',N'LOC-ASSET-0076');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory_EPL&Engg',N'LOC-ASSET-0077');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderabad_Admin',N'LOC-ASSET-0078');
INSERT @Locations VALUES (N'Fujitec NIB Head Office',N'NIB Head Office_Office',N'LOC-ASSET-0079');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_RMS Room',N'LOC-ASSET-0080');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory&HO_Purchase Depart',N'LOC-ASSET-0081');
INSERT @Locations VALUES (N'Fujitec Mumbai1',N'Mumbai1_Sales',N'LOC-ASSET-0082');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Pune1_Sales',N'LOC-ASSET-0083');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory&HO_Engineering Depart',N'LOC-ASSET-0084');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Business support Depart',N'LOC-ASSET-0085');
INSERT @Locations VALUES (N'Fujitec Cochin',N'Cochin_Admin',N'LOC-ASSET-0086');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Finance_Department',N'LOC-ASSET-0087');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_First Aid Room',N'LOC-ASSET-0088');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'1no South side Security Room & 9EPL',N'LOC-ASSET-0089');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Different locations',N'LOC-ASSET-0090');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_cabin 1 Rudrapushpa',N'LOC-ASSET-0091');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_G Flr cabin 31 Alfalfa',N'LOC-ASSET-0092');
INSERT @Locations VALUES (N'Fujitec NIB Head Office',N'NIB Head Office_Manager',N'LOC-ASSET-0093');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Chennai_IT',N'LOC-ASSET-0094');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'CHQ_IT',N'LOC-ASSET-0095');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory&HO_IT',N'LOC-ASSET-0096');
INSERT @Locations VALUES (N'Fujitec Cochin',N'Cochin_IT',N'LOC-ASSET-0097');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Bangalore-IT',N'LOC-ASSET-0098');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Pune1_Admin',N'LOC-ASSET-0099');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Canteen',N'LOC-ASSET-0100');
INSERT @Locations VALUES (N'Fujitec Cochin',N'Cochin_Service',N'LOC-ASSET-0101');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'HO_Service',N'LOC-ASSET-0102');
INSERT @Locations VALUES (N'Fujitec Uttar Pradesh',N'Uttar Pradesh_IT',N'LOC-ASSET-0103');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_HR&Admin',N'LOC-ASSET-0104');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory&HO_Engineering Depart',N'LOC-ASSET-0105');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'HO_HR Office Chennai',N'LOC-ASSET-0106');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Office Orange workstations',N'LOC-ASSET-0107');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Drivers room',N'LOC-ASSET-0108');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory_HOD',N'LOC-ASSET-0109');
INSERT @Locations VALUES (N'Fujitec Haryana-1',N'Haryana1_Service',N'LOC-ASSET-0110');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1',N'LOC-ASSET-0111');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2 cabin 5 Pansy1nos& Quality hall 1nos',N'LOC-ASSET-0112');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Different locations',N'LOC-ASSET-0113');
INSERT @Locations VALUES (N'Fujitec Goa',N'Goa_Office',N'LOC-ASSET-0114');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 1 Rudrapushpa',N'LOC-ASSET-0115');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'HR Department',N'LOC-ASSET-0116');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Pune1_Office',N'LOC-ASSET-0117');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Factory Wings',N'LOC-ASSET-0118');
INSERT @Locations VALUES (N'Fujitec NIB Head Office',N'NIB Head office_IT',N'LOC-ASSET-0119');
INSERT @Locations VALUES (N'Fujitec Mumbai3 (NVM)',N'Mumbai3_Install',N'LOC-ASSET-0120');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Training center',N'LOC-ASSET-0121');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_MWC Warehouse Locker Room',N'LOC-ASSET-0122');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderabad_IT',N'LOC-ASSET-0123');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Fist AID room',N'LOC-ASSET-0124');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Receiption',N'LOC-ASSET-0125');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2',N'LOC-ASSET-0126');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'HO_Corporate Planning',N'LOC-ASSET-0127');
INSERT @Locations VALUES (N'Fujitec Mumbai1',N'Mumbai1_IT',N'LOC-ASSET-0128');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Office Green Workstations',N'LOC-ASSET-0129');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 6 Dahlia',N'LOC-ASSET-0130');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 7 Navmallika',N'LOC-ASSET-0131');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 10 Kumudini',N'LOC-ASSET-0132');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory&HO_Maintenance Depart',N'LOC-ASSET-0133');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Northwing',N'LOC-ASSET-0134');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_ IT Server room',N'LOC-ASSET-0135');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Library Cabin area',N'LOC-ASSET-0136');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 4 Ashok',N'LOC-ASSET-0137');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 17 Orchid',N'LOC-ASSET-0138');
INSERT @Locations VALUES (N'Fujitec NIB Head Office',N'Engg_NIB Head office',N'LOC-ASSET-0139');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 18 Aster',N'LOC-ASSET-0140');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'1no Security Room & 2-Maint Dept Rooom',N'LOC-ASSET-0141');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'South security room 2',N'LOC-ASSET-0142');
INSERT @Locations VALUES (N'Fujitec Jaipur',N'Jaipur_Install',N'LOC-ASSET-0143');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'MPL_Factory & EPL_Factory',N'LOC-ASSET-0144');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_HR & Admin',N'LOC-ASSET-0145');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Vendor Developer',N'LOC-ASSET-0146');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Security room',N'LOC-ASSET-0147');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Office Blue workstations',N'LOC-ASSET-0148');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 8 Neel Kamal',N'LOC-ASSET-0149');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 9 Champakam',N'LOC-ASSET-0150');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Reception',N'LOC-ASSET-0151');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Canteen_VIP dining room',N'LOC-ASSET-0152');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_1st Flr Record room 2',N'LOC-ASSET-0153');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 13 Tulip',N'LOC-ASSET-0154');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 5 Pansy',N'LOC-ASSET-0155');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 2 Marigold',N'LOC-ASSET-0156');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 12 Suryakanti',N'LOC-ASSET-0157');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 20 Iris',N'LOC-ASSET-0158');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 11 Rose',N'LOC-ASSET-0159');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 14 Daisy',N'LOC-ASSET-0160');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 19 Daffodil',N'LOC-ASSET-0161');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 22 Camellia',N'LOC-ASSET-0162');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Maintenance Depart',N'LOC-ASSET-0163');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Warehouse1nos&MPL-2nos',N'LOC-ASSET-0164');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory_Warehouse2ns, Housekeepingroom3nos,EPL2nos',N'LOC-ASSET-0165');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Chennai_Office',N'LOC-ASSET-0166');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'South security room 2',N'LOC-ASSET-0167');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory_Planning Depart',N'LOC-ASSET-0168');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_ 1st Flr Record room 3',N'LOC-ASSET-0169');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 16 Poppy',N'LOC-ASSET-0170');
INSERT @Locations VALUES (N'Fujitec NIB Head Office',N'NIB Head office_Sales',N'LOC-ASSET-0171');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 21 Zinnia',N'LOC-ASSET-0172');
INSERT @Locations VALUES (N'Fujitec Jaipur',N'Jaipur_IT',N'LOC-ASSET-0173');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Entire Factory Land lease cost',N'LOC-ASSET-0174');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_1st Flr Record room 3',N'LOC-ASSET-0175');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory&HO_Purchase Depart',N'LOC-ASSET-0176');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G flr North side Staircase',N'LOC-ASSET-0177');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory&HO_QC',N'LOC-ASSET-0178');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Gfloor north wing_Near to Cabin31',N'LOC-ASSET-0179');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G flr Conference room',N'LOC-ASSET-0180');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Reception',N'LOC-ASSET-0181');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_House keeping store',N'LOC-ASSET-0182');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Canteen',N'LOC-ASSET-0183');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Bangalore_Sales',N'LOC-ASSET-0184');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_1st Flr Record room 4',N'LOC-ASSET-0185');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 3 Kamal',N'LOC-ASSET-0186');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_cabin 15 Lavender',N'LOC-ASSET-0187');
INSERT @Locations VALUES (N'Central Service Warehouse',N'Central Service_Chennai',N'LOC-ASSET-0188');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G flr penal room',N'LOC-ASSET-0189');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Fince Rrd room 3nos& IT-store4nos',N'LOC-ASSET-0190');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Test Tower Basement',N'LOC-ASSET-0191');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Factory_Admin',N'LOC-ASSET-0192');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_House keeping Room',N'LOC-ASSET-0193');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_MWC Warehouse Office',N'LOC-ASSET-0194');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Gfloor near to Escalator',N'LOC-ASSET-0195');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Test Tower',N'LOC-ASSET-0196');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Test Tower 20th flr',N'LOC-ASSET-0197');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Test Tower 17th Flr',N'LOC-ASSET-0198');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building 2_Office Green Workstations',N'LOC-ASSET-0199');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1-G flr North Orange workstations',N'LOC-ASSET-0200');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Frente side',N'LOC-ASSET-0201');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_MWC Warehouse inside',N'LOC-ASSET-0202');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_MWC warehouse south side door',N'LOC-ASSET-0203');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_MWC warehouse Northside',N'LOC-ASSET-0204');
INSERT @Locations VALUES (N'Fujitec Kolkata',N'Kolkata_Install',N'LOC-ASSET-0205');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Chennai_Sales',N'LOC-ASSET-0206');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_RMS Room',N'LOC-ASSET-0207');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Flr IT store',N'LOC-ASSET-0208');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1-G flr Northwing Green workstation',N'LOC-ASSET-0209');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2 cabin_Maintenance',N'LOC-ASSET-0210');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_G flr South side Office door',N'LOC-ASSET-0211');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Near MD cabin',N'LOC-ASSET-0212');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_CMRL room',N'LOC-ASSET-0213');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building 2_Office Orange Workstations',N'LOC-ASSET-0214');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_1st  flr South side',N'LOC-ASSET-0215');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Office work station_Orange',N'LOC-ASSET-0216');
INSERT @Locations VALUES (N'Fujitec Uttar Pradesh',N'Uttar Pradesh_Office',N'LOC-ASSET-0217');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Reliability Depart',N'LOC-ASSET-0218');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Yabuchi',N'LOC-ASSET-0219');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_PCP',N'LOC-ASSET-0220');
INSERT @Locations VALUES (N'Fujitec Delhi',N'Delhi_Sales',N'LOC-ASSET-0221');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Test Tower 10th Flr',N'LOC-ASSET-0222');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st flr Northwing orange workstations',N'LOC-ASSET-0223');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Gfloor North side',N'LOC-ASSET-0224');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_MWC warehouse North side door',N'LOC-ASSET-0225');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Test Tower 18th Flr',N'LOC-ASSET-0226');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory Building renovation work',N'LOC-ASSET-0227');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_IT Server room',N'LOC-ASSET-0228');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Reception.',N'LOC-ASSET-0229');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Test Tower Basement',N'LOC-ASSET-0230');
INSERT @Locations VALUES (N'Fujitec Punjab',N'Punjab_Service',N'LOC-ASSET-0231');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Main Gate',N'LOC-ASSET-0232');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderadad_IT',N'LOC-ASSET-0233');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Test Tower',N'LOC-ASSET-0234');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Delivery Center_ULDC Warehouse',N'LOC-ASSET-0235');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_1st Flr Record room 1',N'LOC-ASSET-0236');
INSERT @Locations VALUES (N'Fujitec Cochin',N'Cochin_Office',N'LOC-ASSET-0237');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'At New Amada Machines_Factory',N'LOC-ASSET-0238');
INSERT @Locations VALUES (N'Fujitec Kolkata',N'Kolkata_Service',N'LOC-ASSET-0239');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_MWC Warehouse_Packing area',N'LOC-ASSET-0240');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1-Canteen',N'LOC-ASSET-0241');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Chennai_ Office',N'LOC-ASSET-0242');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderadad_Br Manager',N'LOC-ASSET-0243');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PC BOOTH_1',N'LOC-ASSET-0244');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_PCP_Lab',N'LOC-ASSET-0245');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_SALVAGNINI-P4',N'LOC-ASSET-0246');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Test tower machine room',N'LOC-ASSET-0247');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Test Tower 1st Flr',N'LOC-ASSET-0248');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_All compressors areas',N'LOC-ASSET-0249');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_CO2 LASER MACHINE',N'LOC-ASSET-0250');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_ETP',N'LOC-ASSET-0251');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PC BOOTH_2',N'LOC-ASSET-0252');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderabad_sales',N'LOC-ASSET-0253');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Purchase Wing',N'LOC-ASSET-0254');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_200 KVA UPS',N'LOC-ASSET-0255');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Factory_PLANT 1 NORTH EAST CORNER',N'LOC-ASSET-0256');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PT LINE 2',N'LOC-ASSET-0257');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Bangalore_Office',N'LOC-ASSET-0258');
INSERT @Locations VALUES (N'Fujitec Cochin',N'Cochin_Sales',N'LOC-ASSET-0259');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PT LINE 1',N'LOC-ASSET-0260');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Test Tower',N'LOC-ASSET-0261');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderabad_Warehouse',N'LOC-ASSET-0262');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_wayment bridge',N'LOC-ASSET-0263');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Security',N'LOC-ASSET-0264');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_cabin 5 Pansy',N'LOC-ASSET-0265');
INSERT @Locations VALUES (N'Fujitec Ahmedabad',N'Ahmedabad_Sales',N'LOC-ASSET-0266');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Stationery room',N'LOC-ASSET-0267');
INSERT @Locations VALUES (N'Fujitec Andhra Pradesh',N'Vijayawada_IT',N'LOC-ASSET-0268');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Showroom seating area',N'LOC-ASSET-0269');
INSERT @Locations VALUES (N'Fujitec Haryana-1',N'Haryana1_Sales',N'LOC-ASSET-0270');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderabad_Office',N'LOC-ASSET-0271');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory_MPL',N'LOC-ASSET-0272');
INSERT @Locations VALUES (N'Fujitec Punjab',N'Punjab_Sales',N'LOC-ASSET-0273');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Locker Room',N'LOC-ASSET-0274');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1st Flr IT store',N'LOC-ASSET-0275');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Quality Hall',N'LOC-ASSET-0276');
INSERT @Locations VALUES (N'Fujitec Ahmedabad',N'Ahmedabad_Engineer',N'LOC-ASSET-0277');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Weighment room',N'LOC-ASSET-0278');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Test Tower 7th flr',N'LOC-ASSET-0279');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_North Side Ladies rest room',N'LOC-ASSET-0280');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Test Tower 18th Flr',N'LOC-ASSET-0281');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Pantry Storage',N'LOC-ASSET-0282');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Test Tower 9th flr',N'LOC-ASSET-0283');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st flr 23 Saffron',N'LOC-ASSET-0284');
INSERT @Locations VALUES (N'Fujitec Uttar Pradesh',N'Uttar Pradesh_Lucknow',N'LOC-ASSET-0285');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st flr Northwing Green',N'LOC-ASSET-0286');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Eastsouth corner',N'LOC-ASSET-0287');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'North Security room 1',N'LOC-ASSET-0288');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_office Rest room',N'LOC-ASSET-0289');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_near to Lift',N'LOC-ASSET-0290');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Canteeen',N'LOC-ASSET-0291');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Panel Room',N'LOC-ASSET-0292');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Flr Cabin 28 Jarul',N'LOC-ASSET-0293');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Flr Cabin 25 Lilac',N'LOC-ASSET-0294');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_IT Depart',N'LOC-ASSET-0295');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_South side',N'LOC-ASSET-0296');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Cabin 31',N'LOC-ASSET-0297');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_ Office Orange workstations',N'LOC-ASSET-0298');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Pune1_ Office',N'LOC-ASSET-0299');
INSERT @Locations VALUES (N'Fujitec Uttar Pradesh',N'Uttar Pradesh_Sales',N'LOC-ASSET-0300');
INSERT @Locations VALUES (N'Fujitec NIB Head Office',N'NIB Head office_Operations',N'LOC-ASSET-0301');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_EPL south Entrance',N'LOC-ASSET-0302');
INSERT @Locations VALUES (N'Fujitec Delhi',N'Delhi_Install',N'LOC-ASSET-0303');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_SHEARING MECHINE',N'LOC-ASSET-0304');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Factory_PLANT 1 OFFICE 1',N'LOC-ASSET-0305');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Factory_PLANT 1 RECEPTION OUTSIDE',N'LOC-ASSET-0306');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_MWC warehouse southside',N'LOC-ASSET-0307');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_1st floor North side',N'LOC-ASSET-0308');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Vehicle Parking area',N'LOC-ASSET-0309');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Pune-1_IT',N'LOC-ASSET-0310');
INSERT @Locations VALUES (N'Fujitec Goa',N'Goa_Install',N'LOC-ASSET-0311');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Parking_Factory',N'LOC-ASSET-0312');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'HO_IT Server Room',N'LOC-ASSET-0313');
INSERT @Locations VALUES (N'Fujitec Goa',N'Goa_Sales',N'LOC-ASSET-0314');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_EPT Plant',N'LOC-ASSET-0315');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_HYDRAULIC PRESS BRAKE-2',N'LOC-ASSET-0316');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_cabin 9 Champakam',N'LOC-ASSET-0317');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderabad_Safety',N'LOC-ASSET-0318');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1st flr_Northwing',N'LOC-ASSET-0319');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1st  flr_southwing',N'LOC-ASSET-0320');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_G flr_Northwing',N'LOC-ASSET-0321');
INSERT @Locations VALUES (N'Fujitec Mumbai3 (NVM)',N'Mumbai3_Offfice',N'LOC-ASSET-0322');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Maintenance Depart',N'LOC-ASSET-0323');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1stFlr 29 Jasmine',N'LOC-ASSET-0324');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_TURRET PUNCHING-2',N'LOC-ASSET-0325');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Gate 3',N'LOC-ASSET-0326');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_MPL_Salvagnini_Bonding line',N'LOC-ASSET-0327');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Floor Sports room',N'LOC-ASSET-0328');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'1 Security room & 1 Maintn',N'LOC-ASSET-0329');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Coimbatore_Office',N'LOC-ASSET-0330');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory_Maitenance',N'LOC-ASSET-0331');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'At weight machine_Factory',N'LOC-ASSET-0332');
INSERT @Locations VALUES (N'Fujitec Uttar Pradesh',N'Uttar Pradesh_Finance',N'LOC-ASSET-0333');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G flr Green workstations',N'LOC-ASSET-0334');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G flr Orange Workstations',N'LOC-ASSET-0335');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Sheet storage-2',N'LOC-ASSET-0336');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Showroom Lift',N'LOC-ASSET-0337');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_MPL_near  to DG set',N'LOC-ASSET-0338');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Gate 2',N'LOC-ASSET-0339');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_1st flr dry Pantry',N'LOC-ASSET-0340');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1stFlr_Northwing_Green',N'LOC-ASSET-0341');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1stFlr_Northwing_Orange',N'LOC-ASSET-0342');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_EPL wiring harness',N'LOC-ASSET-0343');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_cabin 13 Tulip',N'LOC-ASSET-0344');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_MPL GANG WAY-1',N'LOC-ASSET-0345');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_HYDRAULIC PRESS BRAKE-1',N'LOC-ASSET-0346');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_ASSEMBLEY AREA-2',N'LOC-ASSET-0347');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory&HO_Maintenance Room Front',N'LOC-ASSET-0348');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_O2-N2- GAS PLANT',N'LOC-ASSET-0349');
INSERT @Locations VALUES (N'Fujitec Cochin',N'Thulasidas_Sales',N'LOC-ASSET-0350');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Test Tower G flr',N'LOC-ASSET-0351');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_TURRET PUNCHING-1',N'LOC-ASSET-0352');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Warehouse office',N'LOC-ASSET-0353');
INSERT @Locations VALUES (N'Delivery Center',N'Delivery Center_QC',N'LOC-ASSET-0354');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Concrete Weight bridge',N'LOC-ASSET-0355');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_ North G Floor Pantry',N'LOC-ASSET-0356');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1st flr_SouthWing',N'LOC-ASSET-0357');
INSERT @Locations VALUES (N'Fujitec Mumbai1',N'Mumbai1_HR',N'LOC-ASSET-0358');
INSERT @Locations VALUES (N'Fujitec Punjab',N'Punjab_Install',N'LOC-ASSET-0359');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Canteen dining',N'LOC-ASSET-0360');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_AC Pannel room',N'LOC-ASSET-0361');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Entire electrical work',N'LOC-ASSET-0362');
INSERT @Locations VALUES (N'Fujitec Ahmedabad',N'Ahmedabad_Office',N'LOC-ASSET-0363');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_FIBER LASER',N'LOC-ASSET-0364');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory _ Building I & II',N'LOC-ASSET-0365');
INSERT @Locations VALUES (N'Fujitec Jaipur',N'Jaipur_Sales',N'LOC-ASSET-0366');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_PCP_QC',N'LOC-ASSET-0367');
INSERT @Locations VALUES (N'Fujitec Mumbai2',N'Mumbai-2_Install',N'LOC-ASSET-0368');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Test tower lift front side',N'LOC-ASSET-0369');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PANAL BONDING MECHINE',N'LOC-ASSET-0370');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PUMP ROOM FRONT SIDE',N'LOC-ASSET-0371');
INSERT @Locations VALUES (N'Fujitec Punjab',N'Chandigarh_IT',N'LOC-ASSET-0372');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory_PC',N'LOC-ASSET-0373');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1st Flr Southwing Workstations',N'LOC-ASSET-0374');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Driver room inside',N'LOC-ASSET-0375');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_SCARP YARD WEST SIDE',N'LOC-ASSET-0376');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_cabin 6 Dahlia',N'LOC-ASSET-0377');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st flr_Southwing_Green',N'LOC-ASSET-0378');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Gate 1',N'LOC-ASSET-0379');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Mumbai',N'LOC-ASSET-0380');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'CMRL_IT',N'LOC-ASSET-0381');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Flr Cabin 27 Primorse',N'LOC-ASSET-0382');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_EPL Entrance',N'LOC-ASSET-0383');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Receiption counter',N'LOC-ASSET-0384');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Gfloor- Northwing',N'LOC-ASSET-0385');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Canteen',N'LOC-ASSET-0386');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G flr_Manager cabin1',N'LOC-ASSET-0387');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_ASSEMBLEY AREA-4',N'LOC-ASSET-0388');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Factory_PLANT 1 RECPECTION',N'LOC-ASSET-0389');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Sheet storage-1',N'LOC-ASSET-0390');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Showroom entry',N'LOC-ASSET-0391');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_CAR PARKING 2',N'LOC-ASSET-0392');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Service Warehouse',N'LOC-ASSET-0393');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_EPL Test Jig',N'LOC-ASSET-0394');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PC_ UNLOADING AREA',N'LOC-ASSET-0395');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_cabin 17 Orchid',N'LOC-ASSET-0396');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Mumbai-1',N'LOC-ASSET-0397');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Bangalore_Safety',N'LOC-ASSET-0398');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1st flr Northwing',N'LOC-ASSET-0399');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_South side enterance',N'LOC-ASSET-0400');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_HO_admin',N'LOC-ASSET-0401');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Stationery room',N'LOC-ASSET-0402');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory Location',N'LOC-ASSET-0403');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'North Security room 1',N'LOC-ASSET-0404');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_ASSEMBLY AREA 3',N'LOC-ASSET-0405');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_HT YARD GATE',N'LOC-ASSET-0406');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_cabin 4 Ashok',N'LOC-ASSET-0407');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Factory_warehouse Maintenance',N'LOC-ASSET-0408');
INSERT @Locations VALUES (N'Fujitec Mumbai3 (NVM)',N'Mumbai3_Safety',N'LOC-ASSET-0409');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1stFlr_24 Buttercups',N'LOC-ASSET-0410');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1st Flr Cabin 25 Lilac',N'LOC-ASSET-0411');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Pune1_Finance',N'LOC-ASSET-0412');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_LPG PLANT-2',N'LOC-ASSET-0413');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_MPL_Robotic Welding',N'LOC-ASSET-0414');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Weight bridge_ Factory',N'LOC-ASSET-0415');
INSERT @Locations VALUES (N'Fujitec Punjab',N'Punjab_IT',N'LOC-ASSET-0416');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_PCP near',N'LOC-ASSET-0417');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Receiption area',N'LOC-ASSET-0418');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_at Door access reader',N'LOC-ASSET-0419');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Air Condition',N'LOC-ASSET-0420');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Bangalore_IT',N'LOC-ASSET-0421');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_DG YARD',N'LOC-ASSET-0422');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_DRIVER REST ROOM FRONT SIDE',N'LOC-ASSET-0423');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Factory_O2 N2 GAS PLANT FRONT SIDE',N'LOC-ASSET-0424');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_SCRAP YARD',N'LOC-ASSET-0425');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_cabin 8 Neel Kamal',N'LOC-ASSET-0426');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_cabin 7 Navmallika',N'LOC-ASSET-0427');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Bangalore_QC',N'LOC-ASSET-0428');
INSERT @Locations VALUES (N'Fujitec Punjab',N'Punjab_Safety',N'LOC-ASSET-0429');
INSERT @Locations VALUES (N'Fujitec Delhi',N'Delhi_safety',N'LOC-ASSET-0430');
INSERT @Locations VALUES (N'Fujitec Mumbai1',N'Mumbai-1_IT',N'LOC-ASSET-0431');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1st Flr_30 Morning Glory',N'LOC-ASSET-0432');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_MPL @Robot welding',N'LOC-ASSET-0433');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Flr_dry pantry',N'LOC-ASSET-0434');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G flr_Manager cabin2',N'LOC-ASSET-0435');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Next to Factory Electrial Room',N'LOC-ASSET-0436');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Admin&HR_HO',N'LOC-ASSET-0437');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1stfloor Training center',N'LOC-ASSET-0438');
INSERT @Locations VALUES (N'Fujitec Goa',N'Goa_IT',N'LOC-ASSET-0439');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_North side',N'LOC-ASSET-0440');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_PCP near',N'LOC-ASSET-0441');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_cabin 15 Lavender',N'LOC-ASSET-0442');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Head office_Mr.Gopal',N'LOC-ASSET-0443');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_WELDDING',N'LOC-ASSET-0444');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_EPL COP assembly',N'LOC-ASSET-0445');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Factory_PLANT 1 OFFICE 2',N'LOC-ASSET-0446');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PC_LOADING AREA',N'LOC-ASSET-0447');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_SALVAGNINI-S4',N'LOC-ASSET-0448');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_1st flr Northwing Green',N'LOC-ASSET-0449');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_MPL_CO2 laser Machine',N'LOC-ASSET-0450');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1stFlr 26 Lotus',N'LOC-ASSET-0451');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st flr_Southwing_Orange',N'LOC-ASSET-0452');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Flr_Northwing_Discussion table 1',N'LOC-ASSET-0453');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1stFlr_24 Buttercups',N'LOC-ASSET-0454');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st flr_Southwing_Discus table 1',N'LOC-ASSET-0455');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Flr_Finance Recrd room 2',N'LOC-ASSET-0456');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st flr_SouthWing',N'LOC-ASSET-0457');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1stFlr_Northwing',N'LOC-ASSET-0458');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_ G flr Northwing',N'LOC-ASSET-0459');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1 G flr Northwing_Womens restroom',N'LOC-ASSET-0460');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G Flr_Discussion Table 2',N'LOC-ASSET-0461');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1stFlr 29 Jasmine',N'LOC-ASSET-0462');
INSERT @Locations VALUES (N'Fujitec CMRL',N'CMRL_IT',N'LOC-ASSET-0463');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Delivery Center_ULDC warehouse QC',N'LOC-ASSET-0464');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Flr_30 Morning Glory',N'LOC-ASSET-0465');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_EPL Conveyor Line',N'LOC-ASSET-0466');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Flr_Finance Recrd room 1',N'LOC-ASSET-0467');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_EPL Packing Area',N'LOC-ASSET-0468');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1',N'LOC-ASSET-0469');
INSERT @Locations VALUES (N'Fujitec Kolkata',N'Kolkata_Office',N'LOC-ASSET-0470');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G & 1st Floors',N'LOC-ASSET-0471');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G flr Northwing Restroom',N'LOC-ASSET-0472');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1stFlr_Northwing_Discussion table 2',N'LOC-ASSET-0473');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'PUne',N'LOC-ASSET-0474');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G Flr Northwing Discussion Table 1',N'LOC-ASSET-0475');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st flr_Southwing_Discus table 2',N'LOC-ASSET-0476');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st flr Northwing Womens restroom',N'LOC-ASSET-0477');
INSERT @Locations VALUES (N'Fujitec Ahmedabad',N'Ahmedabad_IT',N'LOC-ASSET-0478');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Fujitec_HO',N'LOC-ASSET-0479');
INSERT @Locations VALUES (N'Fujitec Ahmedabad',N'Ahmedabad_Install',N'LOC-ASSET-0480');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Ground Floor',N'LOC-ASSET-0481');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st flr_Southwing toilet',N'LOC-ASSET-0482');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G & 1st Flr Office&canteen area',N'LOC-ASSET-0483');
INSERT @Locations VALUES (N'Fujitec Delhi',N'Delhi_Office',N'LOC-ASSET-0484');
INSERT @Locations VALUES (N'Fujitec Mumbai1',N'Mumbai1_Office',N'LOC-ASSET-0485');
INSERT @Locations VALUES (N'Fujitec Jaipur',N'Jaipur_Office',N'LOC-ASSET-0486');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_1st flr mens restroom',N'LOC-ASSET-0487');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Terrace',N'LOC-ASSET-0488');
INSERT @Locations VALUES (N'Fujitec Andhra Pradesh',N'Andhra Pradesh_Install',N'LOC-ASSET-0489');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Between Building_1 & Building-2',N'LOC-ASSET-0490');
INSERT @Locations VALUES (N'Fujitec Punjab',N'Punjab_Office',N'LOC-ASSET-0491');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1 terrace',N'LOC-ASSET-0492');
INSERT @Locations VALUES (N'Fujitec CMRL',N'CMRL_Office',N'LOC-ASSET-0493');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1 network cables',N'LOC-ASSET-0494');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Fujitec India_Admin',N'LOC-ASSET-0495');
INSERT @Locations VALUES (N'Fujitec Mumbai2',N'Mumbai2_Office',N'LOC-ASSET-0496');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Vendor_Inovance Technology Pvt Ltd',N'LOC-ASSET-0497');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2 canteen & Security Gate-1 store room',N'LOC-ASSET-0498');
INSERT @Locations VALUES (N'Fujitec CMRL',N'CMRL_Install',N'LOC-ASSET-0499');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_MPL LD Conveyor Line 2',N'LOC-ASSET-0500');
INSERT @Locations VALUES (N'Fujitec Haryana-1',N'Factory&HO_IT',N'LOC-ASSET-0501');
INSERT @Locations VALUES (N'Fujitec Kolkata',N'Factory&HO_IT',N'LOC-ASSET-0502');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Factory&HO_IT',N'LOC-ASSET-0503');
INSERT @Locations VALUES (N'Fujitec NIB Head Office',N'NIB Head office_Install',N'LOC-ASSET-0504');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_northside Carparking area',N'LOC-ASSET-0505');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Next to Pupm room',N'LOC-ASSET-0506');
INSERT @Locations VALUES (N'Fujitec Delhi',N'Factory&HO_IT',N'LOC-ASSET-0507');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_MPL_Jamb Assy',N'LOC-ASSET-0508');
INSERT @Locations VALUES (N'Fujitec Mumbai2',N'Mumbai2_IT',N'LOC-ASSET-0509');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_OHC',N'LOC-ASSET-0510');
INSERT @Locations VALUES (N'Fujitec Odisha',N'Odisha_IT',N'LOC-ASSET-0511');
INSERT @Locations VALUES (N'Fujitec Jaipur',N'Factory&HO_IT',N'LOC-ASSET-0512');
INSERT @Locations VALUES (N'Fujitec CMRL',N'CMRL Office',N'LOC-ASSET-0513');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Pump room',N'LOC-ASSET-0514');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Receiption to Canteen',N'LOC-ASSET-0515');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_ASSEMBLY AREA 1',N'LOC-ASSET-0516');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_CAR PARKING 1',N'LOC-ASSET-0517');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Guide Rail Storage Yard',N'LOC-ASSET-0518');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_LPG PLANT-1',N'LOC-ASSET-0519');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Chennai_Finance',N'LOC-ASSET-0520');
INSERT @Locations VALUES (N'Fujitec Mumbai1',N'Mumbai1_safety',N'LOC-ASSET-0521');
INSERT @Locations VALUES (N'Fujitec Mumbai3 (NVM)',N'Mumbai3_Finance',N'LOC-ASSET-0522');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Pune1_Quality',N'LOC-ASSET-0523');
INSERT @Locations VALUES (N'Fujitec Delhi',N'Delhi_Service',N'LOC-ASSET-0524');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Expact',N'LOC-ASSET-0525');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'HO_Operation',N'LOC-ASSET-0526');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_ near to cafetaria Restroom',N'LOC-ASSET-0527');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PACKING AREA-2',N'LOC-ASSET-0528');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PT LINE 3',N'LOC-ASSET-0529');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_ at Weighment',N'LOC-ASSET-0530');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_Entire building',N'LOC-ASSET-0531');
INSERT @Locations VALUES (N'Fujitec Andhra Pradesh',N'Vijayawada_Office',N'LOC-ASSET-0532');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Mangalore_Office',N'LOC-ASSET-0533');
INSERT @Locations VALUES (N'Fujitec CMRL',N'CMRL_Container Office',N'LOC-ASSET-0534');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Hyderabad _Region HO',N'LOC-ASSET-0535');
INSERT @Locations VALUES (N'Fujitec Uttar Pradesh',N'HO_FOD Install Depart',N'LOC-ASSET-0536');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_PCP_PT Line',N'LOC-ASSET-0537');
INSERT @Locations VALUES (N'Fujitec Hyderabad',N'Factory&HO_IT',N'LOC-ASSET-0538');
INSERT @Locations VALUES (N'Fujitec Haryana-1',N'Haryana_IT',N'LOC-ASSET-0539');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-1_Terrace',N'LOC-ASSET-0540');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Pune-1_Install',N'LOC-ASSET-0541');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Quality',N'LOC-ASSET-0542');
INSERT @Locations VALUES (N'Fujitec Ahmedabad',N'Factory&HO_IT',N'LOC-ASSET-0543');
INSERT @Locations VALUES (N'Fujitec Mumbai1',N'Factory&HO_IT',N'LOC-ASSET-0544');
INSERT @Locations VALUES (N'Fujitec Haryana-1',N'Haryana-1_IT',N'LOC-ASSET-0545');
INSERT @Locations VALUES (N'Fujitec Pune-1',N'Factory&HO_IT',N'LOC-ASSET-0546');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_QC',N'LOC-ASSET-0547');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_Gfloor UPS room',N'LOC-ASSET-0548');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Mysore_Office',N'LOC-ASSET-0549');
INSERT @Locations VALUES (N'Fujitec NIB Head Office',N'Factory&HO_IT',N'LOC-ASSET-0550');
INSERT @Locations VALUES (N'Fujitec Mumbai2',N'Mumbai2_Install',N'LOC-ASSET-0551');
INSERT @Locations VALUES (N'Fujitec Kolkata',N'Kolkata_IT',N'LOC-ASSET-0552');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'HO_Admin&HR',N'LOC-ASSET-0553');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Chennai_Install',N'LOC-ASSET-0554');
INSERT @Locations VALUES (N'Fujitec Punjab',N'Punjab-Install',N'LOC-ASSET-0555');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'PUne_Install',N'LOC-ASSET-0556');
INSERT @Locations VALUES (N'Fujitec Andhra Pradesh',N'Vijayawada_Install',N'LOC-ASSET-0557');
INSERT @Locations VALUES (N'Fujitec Kolkata',N'Haryana-1_IT',N'LOC-ASSET-0558');
INSERT @Locations VALUES (N'Fujitec Uttar Pradesh',N'Uttar Pradesh',N'LOC-ASSET-0559');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'Building-2_Server room',N'LOC-ASSET-0560');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-2_MPL',N'LOC-ASSET-0561');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Bangalore-IT',N'LOC-ASSET-0562');
INSERT @Locations VALUES (N'Fujitec Mumbai2',N'Haryana-1_IT',N'LOC-ASSET-0563');
INSERT @Locations VALUES (N'Fujitec Bangalore',N'Mangalore_Install',N'LOC-ASSET-0564');
INSERT @Locations VALUES (N'Fujitec India Pvt Ltd',N'CHQ_Server',N'LOC-ASSET-0565');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Flr Southwing Workstations',N'LOC-ASSET-0566');
INSERT @Locations VALUES (N'Fujitec Andhra Pradesh',N'Vijayawad_Install',N'LOC-ASSET-0567');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_MPL-Assembly & Packing',N'LOC-ASSET-0568');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_MPL next to O2&N2 Gas plant',N'LOC-ASSET-0569');
INSERT @Locations VALUES (N'Fujitec Chennai',N'Chennai_Trichy',N'LOC-ASSET-0570');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory &HO_Admin',N'LOC-ASSET-0571');
INSERT @Locations VALUES (N'Fujitec Mumbai2',N'Factory&HO_IT',N'LOC-ASSET-0572');
INSERT @Locations VALUES (N'Fujitec Mumbai2',N'Mumbai-2_IT',N'LOC-ASSET-0573');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_Warehouse loading/Receiving',N'LOC-ASSET-0574');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PACKING AREA-1',N'LOC-ASSET-0575');
INSERT @Locations VALUES (N'Fujitec Punjab',N'Punjab_HR',N'LOC-ASSET-0576');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Factory_PC',N'LOC-ASSET-0577');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-I_Sports room',N'LOC-ASSET-0578');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_1st Flr_Northwing Rest room',N'LOC-ASSET-0579');
INSERT @Locations VALUES (N'Fujitec Factory Office',N'Building-1_G & 1st Floor',N'LOC-ASSET-0580');
INSERT @Locations VALUES (N'Delivery Center',N'Delivery Center_QC_ULDC warehouse',N'LOC-ASSET-0581');
INSERT INTO [Identity].[OrganizationUnit](OrganizationId,ParentOrganizationUnitId,UnitType,UnitCode,UnitName,IsActive,CreatedAt,UpdatedAt) SELECT @OrganizationId,b.OrganizationUnitId,N'Location',l.Code,l.Name,1,SYSUTCDATETIME(),SYSUTCDATETIME() FROM @Locations l JOIN [Identity].[OrganizationUnit] b ON b.OrganizationId=@OrganizationId AND b.UnitType=N'Branch' AND b.UnitName=l.BranchName WHERE NOT EXISTS(SELECT 1 FROM [Identity].[OrganizationUnit] u WHERE u.OrganizationId=@OrganizationId AND u.UnitType=N'Location' AND u.ParentOrganizationUnitId=b.OrganizationUnitId AND u.UnitName=l.Name);
UPDATE u SET HierarchyPath=p.HierarchyPath+CONVERT(nvarchar(20),u.OrganizationUnitId)+N'/' FROM [Identity].[OrganizationUnit] u JOIN [Identity].[OrganizationUnit] p ON p.OrganizationUnitId=u.ParentOrganizationUnitId WHERE u.OrganizationId=@OrganizationId AND u.UnitType=N'Location' AND u.HierarchyPath IS NULL;
IF EXISTS(SELECT 1 FROM @Branches b LEFT JOIN [Identity].[OrganizationUnit] u ON u.OrganizationId=@OrganizationId AND u.UnitType=N'Branch' AND u.UnitName=b.Name WHERE u.OrganizationUnitId IS NULL) THROW 51002, 'Branch verification failed.', 1;
IF EXISTS(SELECT 1 FROM @Locations l JOIN [Identity].[OrganizationUnit] b ON b.OrganizationId=@OrganizationId AND b.UnitType=N'Branch' AND b.UnitName=l.BranchName LEFT JOIN [Identity].[OrganizationUnit] u ON u.OrganizationId=@OrganizationId AND u.UnitType=N'Location' AND u.ParentOrganizationUnitId=b.OrganizationUnitId AND u.UnitName=l.Name WHERE u.OrganizationUnitId IS NULL) THROW 51003, 'Location verification failed.', 1;
COMMIT;
SELECT UnitType,COUNT(*) AS ActiveCount FROM [Identity].[OrganizationUnit] WHERE OrganizationId=@OrganizationId AND IsActive=1 GROUP BY UnitType ORDER BY UnitType;
SELECT s.UnitName AS StateName,b.UnitName AS BranchName,COUNT(l.OrganizationUnitId) AS LocationCount FROM [Identity].[OrganizationUnit] b JOIN [Identity].[OrganizationUnit] s ON s.OrganizationUnitId=b.ParentOrganizationUnitId LEFT JOIN [Identity].[OrganizationUnit] l ON l.ParentOrganizationUnitId=b.OrganizationUnitId AND l.UnitType=N'Location' AND l.IsActive=1 WHERE b.OrganizationId=@OrganizationId AND b.UnitType=N'Branch' AND b.UnitName IN (SELECT Name FROM @Branches) GROUP BY s.UnitName,b.UnitName ORDER BY s.UnitName,b.UnitName;
